import React from 'react';
import ProjectIntroCS from '../components/ProjectIntroCS';
import RightCS from '../components/RightCS';
import LeftCS from '../components/LeftCS';
import FullCS from '../components/FullCS';
import ThreeCS from '../components/ThreeCS';
import DoubleImgCS from '../components/DoubleImgCS';

import originalscroll from '../assets/images/checkout-original.gif';
import editrecord from '../assets/images/checkout-edit.gif';
import errors from '../assets/images/checkout-errors.png';
import fulfillment1 from '../assets/images/checkout-fulfillment1.png';
import fulfillment2 from '../assets/images/checkout-fulfillment2.png';
import instoreconfirm from '../assets/images/checkout-instore.png';
import expressconfirm from '../assets/images/checkout-express.png';
import commoncarrier from '../assets/images/checkout-commoncarrier.png';
import commercial from '../assets/images/checkout-commercial.png';
import residential from '../assets/images/checkout-residential.png';
import commoncarriergif from '../assets/images/checkout-commoncarrier.gif';
import addressgif from '../assets/images/checkout-address2.gif';
import final from '../assets/images/checkout-final.png';
import finalscroll from '../assets/images/checkout-finalscroll.gif';

function Checkout({ uxProjects, projectIndex}) {
    const project = uxProjects[projectIndex];
    return (
        <div className="case-study__wrapper">
            <ProjectIntroCS project={project}/>
            <FullCS header="Overview" subtitle="The Restaurant Store is a major e-commerce restaurant supplier, but its checkout experience lacked the clarity, flexibility, and usability that customers needed to confidently complete purchases." textContent={"I led the redesign of The Restaurant Store’s checkout flows to reduce friction, increase form clarity, and reduce complexity to better support fast-moving, high-volume buyers.\nThrough hands-on design and research, I improved mobile input behaviors, optimized form layout and error handling, and implemented subtle UI enhancements to reduce cognitive load. These changes directly addressed key usability pain points and prepared the checkout flow for measurable improvements in conversion, speed, and customer satisfaction once launched."}></FullCS>
            <FullCS className="case-study__bg" header="Problem Statement" subtitle="In just a month, 3,000 customers generated over $929,000 in revenue, but nearly half dropped off during checkout. Busy foodservice professionals faced preventable checkout friction: unclear address defaults, poor error messaging, inability to edit key information, and fulfillment option confusion." textContent={"How might we improve checkout to help busy foodservice professionals easily place orders without technical frustration?"}></FullCS>
            <h2 className="case-study__section-title case-study__padding"><span class ="title__break">|</span> research and definition</h2>
            <RightCS  header="Collaborative Research" subtitle="Before building a solution, we needed to understand our users. We analyzed feedback and user sessions to identify key pain points." textContent={"We reported actionable recommendations such as:"} listContent={"Allowing users to edit account and order details directly in checkout.\nImprove fulfillment option clarity throughout the user flow so that user expectations are aligned with their order method.\nRefine form layout and validation logic to reduce cognitive load, especially for mobile users and when multiple errors are present.\nClarifying default selections for payment and address fields to support fast-faced users goals."} imgLabel="Original Page" img={originalscroll} imgAlt={"Scrolling gif of The Restaurant Store's original checkout page, showing all fulfillment order types and excessive alerts."}></RightCS>
            <ThreeCS header="Defining The Problem" subtitle="For our MVP, we focused on these core features discovered from user interviews, a feature priority matrix, and ideal user flows." statTitle="Efficiency" statText="Improve form layout, default behavior, and mobile-usability to increase task speed for users." statTitle2="Flexibility" statText2="Allow customers to easily edit personal and order information without leaving the checkout flow." statTitle3="Clarity" statText3="Increase confidence by improving user feedback and resolving fulfillment option confusion."></ThreeCS>
            <h2 className="case-study__section-title case-study__bg case-study__padding"><span class ="title__break">| </span> wireframing and prototyping</h2>
            <RightCS className="case-study__bg" header="Wireframing Initial Solutions" subtitle="I turned our research findings into updated wireframes, connecting our insights to visual solutions." textContent={"At this stage, we began with overall updates to utilize our updated design system to improve feedback clarity and communicate information at a glance:"} listContent={"Updated form stylings to follow design pattern best practices.\nMocked up error patterns for single and multi-error summaries.\nAdded contextual UI enhancements (quantity indicators, dynamic labels, primary tags, etc.)"} img={errors} imgAlt={"A wireframe of an error alert pattern with an error summary and inline messaging."} imgLabel="Error summary and form updates example" imgDescription={"I researched best practices for form UI and error patterns and documented them for our team. This example shows an error summary for a form-level submission with multiple errors."}></RightCS>
            {/*<FullCS className="case-study__bg" header="Wireframing Initial Solutions" subtitle="I turned our research findings into updated wireframes, connecting our insights to visual solutions." textContent={"At this stage, we began with overall updates to utilize our updated design system to improve feedback clarity and communicate information at a glance:"} listContent={"Updated form stylings to follow design pattern best practices.\nMocked up error patterns for single and multi-error summaries.\nAdded contextual UI enhancements (quantity indicators, dynamic labels, primary tags, etc.)"}></FullCS>*/}
            <LeftCS className="case-study__bg" header="Checkout Flow and Flexibility" subtitle="We redesigned checkout to allow inline editing, removing the need to leave checkout to make simple updates and keeping users engaged in a linear checkout flow." textContent={"User session recordings showed 433 users in a monthly period trying to edit their contact and personal details during checkout, leading to friction and drop-off.\nUsing this average of impacted users, these changes should improve the checkout flow experience for ~15% of users upon launch."} imgLabel="Editable Information" img={editrecord} imgAlt={"A recording of user editing contact information."}></LeftCS>
            <DoubleImgCS className="case-study__bg" header="Clarifying Fulfillment Options and Next Steps" subtitle="Users often struggled to distinguish between in-store pickup and “Express” drive up, leading to confusion during and after checkout over The Restaurant Store’s fulfillment options, so we mocked up improvements at checkout and order confirmation." textContent={"The original design buried critical details in an alert users skipped, lacked a pickup date, and only vaguely explained that Express required pre-payment.\n Partnering with product and development to work within the constraints that pickup type depends on payment method, I designed a new solution that clearly communicated fulfillment logic without overwhelming users."} imgLabel="Original Pickup" img={fulfillment1} imgAlt={"A screenshot of the current pickup option, described above."} img2={fulfillment2} imgLabel2="Updated Pickup" imgAlt2={"A mockup of updated pickup utilizing better alerts usage and explaining in-store and express pickup differences."}></DoubleImgCS>
            <DoubleImgCS className="case-study__bg" subtitle="We updated fulfillment sections across the checkout flow to clearly denote how payment impacted a pick up order being in-store or Express."textContent={"While redesigning the confirmation page, I added clearly-labeled, tailored next steps by order type to ensure customers knew what to expect post-purchase."} imgLabel="In-Store Pickup Confirmation" img={instoreconfirm} imgAlt={"A wireframe of updated in-store confirmation information and steps telling users to come in store to finish and collect their order."} img2={expressconfirm} imgLabel2="Express Pickup Confirmation" imgAlt2={"A wireframe of updated express confirmation steps telling users where to park to collect their order."}></DoubleImgCS>
            <h2 className="case-study__section-title case-study__padding"><span class ="title__break">| </span> usability testing and iterating</h2>
            <RightCS header="Address Selection Iterations" subtitle="While enabling in-checkout editing, auditing UI patterns revealed the dropdown UI made address selection and updates overly complex so we prototyped a new solution." textContent={"By mirroring patterns from our account dashboard and other e-commerce sites, we introduced a card-based interface.\nThis made it easier for users to review, select, and edit addresses without leaving checkout, reducing friction and preventing duplicate entries."} imgLabel="Updated Address Selection" img={addressgif} imgAlt={"A recording of a user interacting with the updated address selection card, clicking to open a menu to change their address, edit, or delete it."} Link="https://www.figma.com/proto/TtxBptdhvKsN6JjJj8VTej/Cart---Checkout-2025?page-id=3274%3A37718&node-id=3274-39741&viewport=8993%2C-8312%2C0.25&t=Kk0ELgNrT24VaFzB-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3274%3A39741" LinkText="View address selection prototype"></RightCS>
            <LeftCS header="Common Carrier Shipping Iterations" subtitle="Session recordings revealed confusion around carrier contact opt-ins. To address this, we redesigned the UI based on address type and delivery needs." textContent={"While improving fulfillment options, we found that users were confused by a required checkbox that looked optional. Many tried to opt out of carrier contact, slowing them down and creating frustration.\nI redesigned this step with feedback from customer service to:"} listContent={"Remove the misleading checkbox, replacing it with UI clearly showing if carrier contact is optional or required.\nTailor messaging and interaction based on whether the address was business or residential.\nProvide information in context rather than an alert users skipped over.\nInclude clear next steps on the confirmation page accurately reflecting their call preferences."} imgLabel="Original Common Carrier Order" img={commoncarrier} imgAlt={"A screenshot of the original common carrier order, showing a confusing phone number, disabled checkbox, and a lengthy alert."}></LeftCS>
            <DoubleImgCS imgLabel="Residential Address UI" img={residential} imgAlt={"A mockup of a common carrier order for residential address selection. It uses a checkbox marked as required to show calling and scheduling a delivery is required and moves content in-line with the rest of order information."} img2={commercial} imgLabel2="Commercial Address UI" imgAlt2={"A mockup of a common carrier order for commercial address selection using radio UI to show their choices and uses the same improved information hiearchy as the residential order."}></DoubleImgCS>
            {/*<FullCS img={commoncarriergif2} imgAlt2={"."} imgLabel="Common Carrier Confirmation Steps"></FullCS>
            <FullCS img={commoncarriergif} imgAlt2={"."} imgLabel="Common Carrier Confirmation Steps"></FullCS>*/}
            <LeftCS header="Prototype Testing and Iteration Results" subtitle="Building rapid prototypes during our design process gave us the opportunity to test functionality of our designs in real time and make choices informed by feedback. " textContent={"Insights from testing helped us refine layout, form clarity, and interaction to make iterations with confidence. Usability testing showed a ~30% increase in task efficiency with users completing key checkout steps faster and with less friction.\nTo prepare for development and launch, I led wireframe calls to stay aligned with developers and stakeholders, then delivered high-fidelity mockups with annotations for handoff."} imgLabel="Common Carrier Confirmation Steps" img={commoncarriergif} imgAlt={"An animation scrolling between common carrier steps, showing different variants for if users opted into the phone call preference or not."}></LeftCS>
            {/*<FullCS header="From Prototype Testing to Final Implementation" subtitle="Building rapid prototypes during our design process gave us the opportunity to test functionality of our designs in real time and make choices informed by feedback. " textContent={"Insights from testing helped us refine layout, form clarity, and interaction to make iterations with confidence. Usability testing showed a ~30% increase in task efficiency with users completing key checkout steps faster and with less friction.\nTo prepare for development and launch, I led wireframe calls to stay aligned with developers and stakeholders, then delivered high-fidelity mockups with annotations for handoff."}></FullCS>
            <DoubleImgCS header="Common Carrier Shipping Iterations" subtitle="Session recordings revealed confusion around carrier contact opt-ins. To address this, we redesigned the UI based on address type and delivery needs." textContent={"While improving fulfillment options, we found that users were confused by a required checkbox that looked optional. Many tried to opt out of carrier contact, slowing them down and creating frustration.\nI redesigned this step with feedback from customer service to:"} listContent={"Remove the misleading checkbox, replacing it with UI clearly showing if carrier contact is optional or required.\nTailor messaging and interaction based on whether the address was business or residential.\nProvide information in context rather than an alert users skipped over.\nInclude clear next steps on the confirmation page."} imgLabel="Residential" img={residential} imgAlt={"."} img2={commercial} imgLabel2="Commercial" imgAlt2={"."}></DoubleImgCS>*/}
            <h2 className="case-study__section-title case-study__padding case-study__bg"><span class ="title__break">|</span> the final product and impact</h2>
            <FullCS className="case-study__bg" img={final} imgAlt2={"A mockup of the updated checkout experience showing the primary checkout page and order confirmation page across multiple devices."}></FullCS>
            {/*<LeftCS className="case-study__bg" header="Projected Impact" subtitle="To evaluate whether the redesigned checkout experience resolves key usability issues and reduces customer friction, I recommended a set of core KPIs to track post-launch." textContent={"These metrics will help determine if the new flow supports faster, confident order completion:"} listContent={"Reduced checkout time, especially on mobile, by simplifying address selection and error handling.\nLower drop-off rate during fulfillment and payment steps due to clearer feedback and inline editing\nImproved completion rate for orders with better messaging and next-step guidance\nFewer duplicate address entries through reusable, editable card patterns"} imgLabel="Final Scroll-Through" img={checkoutgif} imgAlt={"."}></LeftCS>*/}
            <LeftCS className="case-study__bg" header="Projected Impact" subtitle="Based on previous research data and observed drop-off points, the redesign is predicted to reduce cart abandonment by ~10% once launched, supporting faster, confident orders." textContent={"To evaluate if the redesigned checkout experience resolves key usability issues and reduces customer friction, I recommended core KPIs to track:"} listContent={"Reduced checkout time, especially on mobile, by simplifying address selection and error handling.\nLower drop-off rate during fulfillment and payment steps due to clearer feedback and inline editing\nImproved completion rate for orders with better messaging and next-step guidance\nFewer duplicate address entries through reusable, editable card patterns"} imgLabel="Final Scroll-Through" img={finalscroll} imgAlt={"A scrolling gif of the updated checkout page showing improved pickup information, updated form styling, and editable contact and order information."}></LeftCS>
            <div className="case-study__button-wrap case-study__bg case-study__padding">
                <a href="https://www.figma.com/proto/TtxBptdhvKsN6JjJj8VTej/Cart---Checkout-2025?page-id=40000062%3A92208&node-id=40000062-92209&viewport=129%2C310%2C0.5&t=TFzBnk5ksUpdI7Es-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=40000062%3A92209" className="contactForm__button case-study__link">Checkout prototype here<i class="fa-solid fa-arrow-right"></i></a>
                <a href="https://www.figma.com/proto/TtxBptdhvKsN6JjJj8VTej/Cart---Checkout-2025?page-id=40000062%3A92208&node-id=40000062-93749&viewport=129%2C310%2C0.5&t=TFzBnk5ksUpdI7Es-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=40000062%3A93749" className="contactForm__button case-study__link button__secondary">Order confirmation prototype here<i class="fa-solid fa-arrow-right"></i></a>
            </div>
            <FullCS className="case-study__bg" header="Conclusion" subtitle="Final thoughts:" textContent={"As the UI Designer leading the redesign of the checkout flow, I thrived taking ownership of the flow, refining little details, coordinating consistent design patterns between cart and checkout, and iterating to get the best solutions possible.\n I learned more about meeting the needs of different user types through dynamic content, deepened my understanding of our fulfillment types, and got to take charge of a complicated end-to-end project with many pieces.\nI am grateful to have collaborated with my product design team, development, and customer service to a deliver a solution aligned with our user and business needs."}></FullCS>
        </div>
    );
}

export default Checkout;